name: 'CI'

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Extract node version
        id: package
        run: |
          echo ::set-output name=node::$(jq --raw-output .engines.node ./package.json)
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.package.outputs.node }}
          cache: ${{ !env.ACT && 'npm' || '' }}
      - name: Install dependancies
        run: npm ci
      - name: Run Lint
        run: npm run lint -s
      - name: Check format
        run: npm run format:check
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Extract node version
      id: package
      run: |
        echo ::set-output name=node::$(jq --raw-output .engines.node ./package.json)
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.package.outputs.node }}
        cache: ${{ !env.ACT && 'npm' || '' }}
    - name: Install dependancies
      run: npm ci
    - name: Run Build
      run: npm run build -s
